[versions]
android = "8.6.0"
kotlin = "2.0.20"

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
android-application = { id = "com.android.application", version.ref = "android" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version = "2024.09.00" }
compose-material3 = { module = "androidx.compose.material3:material3" }

ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.2" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.8.5" }
